[pytest]
testpaths = tests
minversion = 9.1
norecursedirs = .venv .pytest_cache work allure-results allure-report allure-clean-install allure-rerun allure-rerun2 artifacts __pycache__
addopts = -ra --strict-markers --strict-config
markers =
    calendars: calendar page
    modals: modal dialogs
    ads: delayed advertisement
    form_fields: form fields page
timeout = 60
timeout_method = thread
